name: Security Workflows 

on:
  push:
    branches: [ dev, staging, dev-1062 ]
    tags: [ 'v*.*.*' ]
   
jobs:
  container-scan:
    runs-on: th879
    environment: ${{ github.head_ref || github.ref_name }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps: 
      - name: Run Container Security Scan Action
        uses: USEPA/ccte-container-scan@main
        with:
          image_name: vue_chemical_transformation_AEM-security-cs
          dockerfile: Dockerfile
          output_path: ./output/chet-vue-report.html
          cleanup_path: /data/watchtower/chet/container-results/chet-ui/chet-vue-report.html
          watchtower_path: /data/watchtower/chet/container-results/chet-ui/chet-vue-report.html

  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Run Scan
      uses: USEPA/ccte-secret-scan@main
      with:
        base_branch: ${{ github.event.repository.default_branch }}

  
      
